language: csharp
solution: Unosquare.WaveShare.FingerprintModule.sln
dotnet: 2.0.0
dist: trusty
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
install:
  - msbuild /t:Restore
script:
  - msbuild /p:Configuration=Release
